### ISSUE TITLE
release 0.1.1 from current trunk, to work with current rustc

### ISSUE THREAD

**Issue by warner** [vladikoff/rust-hkdf#3]
The 0.1.0 release (the latest on crates.io) won't compile with the current version of Rust, because of a syntax change that happened back in the rustc-1.5.0 era. The fix for that is on current master, so the only thing that needs to be done is to make a 0.1.1 release (modify Cargo.toml, tag, publish).

I'm about to file a PR that changes the API (and the dependencies) to use RustCrypto, which is more modern and apparently more popular than rust-crypto. That new API will need a new major release (0.2.x), so I figure maybe we should publish at least one functional crate using the old API first.

I'm happy to drive that release if you want.

thanks!

**Comment by vladikoff** [comment]
Done! Thank you Brian!
